{{- if .Values.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
{{- include "weave-scope-frontend.helm_std_labels" . | indent 4 }}
    kubernetes.io/ingress.class: "nginx-internal"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: "{{ .Release.Namespace }}-ingress"
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.global.service.hostname }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.global.service.name | default (include "toplevel.fullname" .) }}
              servicePort: {{ .Values.global.service.port }}
            path: /   
{{- end -}}
