{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kibana.serviceAccountName" . }}
  labels:
    app: {{ template "kibana.name" . }}
    chart: {{ template "kibana.chart" . }}    
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end }}
