apiVersion: enterprises.upmc.com/v1
kind: ElasticsearchCluster
metadata:
  name: {{ .Release.Name }}-cluster
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ template "elasticsearch.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{ toYaml .Values.spec | indent 2 }}
