alertmanager:
  enabled: true
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx-internal
    hosts: 
      - alertmanager.demo.contoso.com
server:
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx-internal
    hosts: 
      - prometheus.demo.contoso.com

