dependencies:
- name: fluent-bit
  version: "1.3.0"
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: elasticsearch-curator
  version: "1.0.1"
  repository: https://kubernetes-charts.storage.googleapis.com/
